import { MantineProvider } from "@mantine/core";
import Banner from "n/components/Banner";
import Footer from "n/components/Footer";
import Header from "n/components/Header";
import LargerCart from "n/components/LargerCart";
import MediumCard from "n/components/MediumCard";
import SmallCards from "n/components/SmallCards";
import Head from "next/head";

export default function Home({ exploreData, cardsData }) {
  return (
    <>
      <Head>
        <title>RJ Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        theme={{
          /** Put your mantine theme override here */
          colorScheme: "light",
        }}
      >
        <main>
          <Header />
          <Banner />
          <section className="max-w-7xl mx-auto px-6 sm:px-16">
            {/* explore nearby page */}
            <h2 className="text-2xl sm:text-4xl font-semibold py-5 m-0">
              Explore NearBy
            </h2>

            {/* small cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 ">
              {exploreData.map((item) => (
                <SmallCards
                  key={item.location}
                  img={item.img}
                  location={item.location}
                  distance={item.distance}
                />
              ))}
            </div>

            {/* live anywhere */}
            <h2 className="text-2xl sm:text-4xl font-semibold py-8 m-0">
              Live Anywhere
            </h2>

            <div className="flex gap-4 overflow-scroll scrollbar-hide -ml-3  p-3">
              {cardsData.map((item) => (
                <MediumCard key={item.img} img={item.img} title={item.title} />
              ))}
            </div>

            {/* largeCart */}
            <LargerCart
              img="https://links.papareact.com/4cj/"
              title="The Greated Outdoors"
              description="Whishlists curated by Airbnb"
              buttonTxt="Get Inspired"
            />
          </section>
        </main>

        {/* footer */}
        <Footer />
      </MantineProvider>
    </>
  );
}

export async function getStaticProps() {
  const res1 = await fetch("https://www.jsonkeeper.com/b/4G1G");
  const res2 = await fetch("https://www.jsonkeeper.com/b/VHHT");
  const exploreData = await res1.json();
  const cardsData = await res2.json();

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
